on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/learning-react
            if [ ! -d ".git" ]; then
              echo "First deploy → clone repo"
              git clone -b staging git@github.com:pho2345/learning-react.git .
            else
              echo "Pull latest changes"
              git pull origin staging
            fi

            pnpm install
            pnpm build
            pnpm start
